AWSTemplateFormatVersion: "2010-09-09"

Parameters:
  VpcId:
    Type: String
    Description: ID of the existing VPC
  SubnetId:
    Type: String
    Description: ID of the existing subnet
  KeyPairName:
    Type: String
    Description: Name of the existing Key Pair

Resources:
  BastionInstance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-00b1c9efd33fda707
      InstanceType: t2.micro
      SubnetId: !Ref SubnetId
      KeyName: !Ref KeyPairName  # Use the provided KeyPairName parameter
      SecurityGroupIds:
        - !Ref BastionSecurityGroup
      UserData:
        Fn::Base64: |
          #!/bin/bash
          yum update -y
          yum install -y git
          curl --silent --location "https://dl.k8s.io/release/$(curl --silent --location https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl" -o /usr/local/bin/kubectl
          chmod +x /usr/local/bin/kubectl
          curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
          mv /tmp/eksctl /usr/local/bin
          chmod +x /usr/local/bin/eksctl
      Tags:
        - Key: Name
          Value: BastionInstance

  BastionSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for the Bastion instance
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: BastionSecurityGroup
