apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-dbcrudmicro
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dbcrudmicro
  template:
    metadata:
      labels:
        app: dbcrudmicro
    spec:
      serviceAccountName: kc-service-account
      containers:
        - name: back-end
          image: 636587819181.dkr.ecr.eu-west-1.amazonaws.com/dbcrudmicro:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8081
          env:
            - name: CB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: username
            - name: CB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secret
                  key: password